### ISSUE TITLE
required input schema for customized datasets

### ISSUE THREAD

**Issue by julia78118** [facebookresearch/CPA#3]
Hi, 
Thanks for making this public! 
I am wondering what is the required schema for the input in order to train CPA on our own datasets?

**Comment by M0hammadL** [comment]
Hi @julia78118 
Thanks for the interest. 
I guess the best thing would be to look into one of the notebooks in the [preprocessing](https://github.com/facebookresearch/CPA/tree/master/preprocessing) folder. This will basically show how you can load a dataset and add additional fields to the data structure to make it ready to be fed to CPA. This will include specifying the covariate labels (if you have any like cell_types) and perturbation labels and splitting the data into, train, test and OOD (this was done for the sake of the paper and if you don't have ood data just use part of test data as ood to be compatible with the model). 

According to the type of data:
- If you have single-cell KO + combination of KOs (CROP-seq, perturb-seq) check [this](https://github.com/facebookresearch/CPA/blob/master/preprocessing/Norman19.ipynb) notebook.
- if you a  dataset with perturbations and covariates check `preprocessing/GSM.ipynb` or `/preprocessing/cross_species.ipynb` .

Hope this solves your problem.
Mo
